### ISSUE TITLE
Add tests for SRI/CORS on CSS and Javascript files

### ISSUE THREAD

**Issue by fulldecent** [fulldecent/html-website-template#15]
Upstream issues:

* https://github.com/gjtorikian/html-proofer/issues/406
* https://github.com/gjtorikian/html-proofer/issues/400

**Comment by ilyalyo** [comment]
Added PRs:
https://github.com/gjtorikian/html-proofer/pull/412
https://github.com/gjtorikian/html-proofer/pull/413

**Comment by fulldecent** [comment]
Waiting for upstream to release v3.6.1 so we can update gemfile.

**Comment by fulldecent** [comment]
Fixed in fa757fe1d225a2629bd46fca1b96e8047fe3975a
