### ISSUE TITLE
Add tests for JS validation

### ISSUE THREAD

**Issue by fulldecent** [fulldecent/html-website-template#18]
# Discussion 

Somehow we should validate al JS is valid. There is probably already a tool for this.

**Comment by ilyalyo** [comment]
I found this one: https://github.com/stereobooster/jshintrb
It can be used with rake:
```
require "jshintrb/jshinttask"
Jshintrb::JshintTask.new :jshint do |t|
  t.pattern = 'javascript/**/*.js'
  t.options = :defaults
end
```

**Comment by fulldecent** [comment]
This looks good, let's try it!

**Comment by fulldecent** [comment]
Actually that project looks dead. Maybe there is a better-maintained JSHint Ruby wrapper elsewhere.

**Comment by ilyalyo** [comment]
I found a few more, but they are also not maintained.
Travis comes with Node.js and Ruby pre-installed ([link](http://stackoverflow.com/a/31373752/5552925)) so we can use jshint with npm.
[npm jshint](http://jshint.com/install/)

**Comment by fulldecent** [comment]
I am not sure yet if I want to use NPM. This would add a build dependency for html-website-template.

**Comment by fulldecent** [comment]
no clear path forward here, closing
