### ISSUE TITLE
Add amazing travis file that checks for all kinds of stuff

### ISSUE THREAD

**Issue by fulldecent** [fulldecent/html-website-template#2]
- [x] Update `.travis.yml` to call `bundler exec rake test`

Then add these things below into our `lightning_sites.rb`.  Prefer to use the `sh html-proofer ...` approach rather than native ruby implementation, if it will save time!

- [x] Validate HTML using `htmlproofer --check-external-hash --check-favicon --check-html --check-img-http --check-opengraph --enforce-https --timeframe 30d
`
- [ ] Test line endings - see https://github.com/mcandre/lili
- [ ] Find a way to validate things for accessibility, see https://tenon.io/testNow.php?url=http://acls.net
- [x] Ensure `<link>` or `<script>` go to https websites (done, use `--enforce-https` above)
- [x] Any `<link>` and `<script>` tags to external resources should use subresource integrity and CORS, see https://github.com/gjtorikian/html-proofer/issues/382)
- [ ] Check that `mailto:` links are awesome (include a subject or body)
- [ ] Ensure the existence of XML sitemap
    https://support.google.com/webmasters/answer/156184?hl=en
    > However, in most cases, your site will benefit from having a sitemap, and you'll never be penalized for having one.
- [ ] Validate CSS files
- [ ] Validate JS files
- [ ] Use webpuc https://github.com/fulldecent/web-puc

## Separate `test_extensive` task

- [ ] Only check external links in this task

## Tests that work on a served version of the site (i.e. `php -S localhost:8000`)

 - [ ] Make sure site redirects to HTTPS

Currently we use this for travis:
```
language: ruby
rvm:
- 2.2.5

script:
 - bundle exec jekyll build
 - bundle exec htmlproofer ./_site

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build
```

**Comment by fulldecent** [comment]
Other low priority items:

1. Do not duplicate META descriptions across pages
2. Do not duplicate TITLE tags across pages
3. Validate HTML source code is valid

Uncompressed images

1. https://developers.google.com/speed/docs/insights/OptimizeImages
   As a result, optimizing images can often yield some of the largest byte savings and performance improvements: the fewer bytes the browser has to download, the less competition there is for the client's bandwidth and the faster the browser can download and render content on the screen.

**Comment by VirenMohindra** [comment]
great stuff -- will definitely be watching this project.

Couldn't find the `--timeframe` flag in the docs and your usage helped fix my failing builds in travis CLI

Cheers

**Comment by fulldecent** [comment]
Thank you! FYI, here is more discussion about `--timeframe` and making it work with continuous integration. (Still an unsolved topic.)

https://github.com/gjtorikian/html-proofer/issues/381

**Comment by fulldecent** [comment]
@VirenMohindra Thanks again, FYI, we are now 1.0.0

**Comment by fulldecent** [comment]
Broke this issue into individual items, closing.

#15, #16, #17, #18, #19, #20
