### ISSUE TITLE
Add tests for old versions of Bootstrap and other includes

### ISSUE THREAD

**Issue by fulldecent** [fulldecent/html-website-template#20]
# Discussion

Web projects include Bootstrap and all kinds of jQuery plugins. Check each one to see if there is a newer version available and fail the test if true.

# Work plan

- [ ] Review this tool to confirm it works https://github.com/fulldecent/web-puc
- [ ] Integrate it into this project's test suite

**Comment by ilyalyo** [comment]
Added PR for web-puc with tests and small fixes: [web-puc PR](https://github.com/fulldecent/web-puc/pull/8)
Added PR to lightning-sites with new web-puc task: [lightning-sites PR](https://github.com/fulldecent/lightning-sites/pull/14/commits)
And also updated STAT, moved dependencies to gemspec: [STAT PR](https://github.com/fulldecent/structured-acceptance-test/pull/39)

I updated gemspecs files in web-puc and STAT, we need to republish them to rubygems, before merging ligthsite PR.

**Comment by fulldecent** [comment]
All of these are merged. Also, I released lightning-sites 1.0.9 gem.

**Comment by fulldecent** [comment]
We can now use the updated gem here.
